### ISSUE TITLE
Improve and add contents

### ISSUE THREAD

**Issue by Astrodevil** [ZeroOctave/resource-gallery#1]
Original Issue: [Check here](https://github.com/Astrodevil/Open-Source-Gallery/issues/3).

Thinking of shipping the current resource gallery ( [GitHub](https://mranand.com/Open-Source-Gallery/) and [Live](https://mranand.com/Open-Source-Gallery/) link) on a fully responsive website by using site generators and themes of **Hugo** or **Astro**.

[doks theme](https://getdoks.org/) and [astroship theme](https://astro.build/themes/details/astroship/)

If you are interested to contribute, you are welcome🙏🏼

New website codes will be hosted [here](https://github.com/Astrodevil/resource-gallery): make pull requests after changes.

**What will be added:**
- More resources
- Blogs
- Programs

### Currently using [Astro](https://astro.build/) theme [Astroship](https://astro.build/themes/details/astroship/)

Need to work on **resource** and **quick links** section. The update codes are present in [this](https://github.com/Astrodevil/resource-gallery) repo, clone and run on your machine to check and update.

![image](https://user-images.githubusercontent.com/73425223/213997371-3e7b21fa-243d-49a5-961a-77427c57bc22.png)

Take docs, orientation, cards, navs suggestions from [here](https://astro.new/). This website has various theme layouts that can be used in our project to improve.

**Comment by Astrodevil** [comment]
Above work is done, now need contents

What will be added:

    More resources
    Blogs
    Programs

**Comment by raj3000k** [comment]
Hi, @Astrodevil  I can add More Content and Blogs related to React, Blockchain, and other various stuff,
Blogs like Top 10 common errors while getting started with react xyz Top 10 JS tricks....

These types of blogs/resources would be really helpful for beginners to get started.
You can assign me this under GSSOC 23. ☺️

**Comment by Astrodevil** [comment]
Are the blogs your original creation? or re-sharing your own blogs. Please avoid AI generated blogs.

**Comment by raj3000k** [comment]
@Astrodevil  ? any update. + Do I need to send a new PR again as there are new updates in the main branch ?
