### ISSUE TITLE
🐛 [BUG] - <title>

### ISSUE THREAD

**Issue by AbhayaShankar** [ZeroOctave/resource-gallery#103]
## 🐛 Bug Report Form

|                |                     |
|----------------|---------------------|
| **Description** | The Navbar seems to create issue with the rest of the Webpage. |
| **Reproduction URL** | Please provide your GitHub URL to reproduce the issue |
| **Reproduction Steps** | 1. Step 1. One thing you can implement is background: transparent;
backdrop-filter: blur(8px);  - this would give a nice overall view to the UI, without conflicting issues.
<br> |
| **Screenshots** | ![image](https://github.com/ZeroOctave/resource-gallery/assets/113185442/87838c76-39c2-4c5b-b399-32e1ef35a5bf) |
| **Logs** | Relevant log output goes here |
| **Additional Context** | Please provide any other relevant information about the problem |

🌐 **Browsers**
Which browsers are you experiencing the problem on? (Select all that apply)

- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Opera
- [ ] Brave

💻 **OS**
What is the impacted environment (operating system)? (Select all that apply)

- [x] Windows
- [ ] Linux
- [ ] Mac
- [ ] iOS
- [ ] Android

📝 **Sections Completed**
Check the box of the sections you have completed:

- [ ] Description
- [ ] Reproduction URL
- [ ] Reproduction Steps
- [x] Screenshots
- [ ] Logs
- [x] Browsers
- [ ] OS
- [x] Additional Context

🔍 **Priority**
Please select the priority of the bug:
- [x] High
- [ ] Medium
- [ ] Low

📜 **Code of Conduct**
By submitting this issue, you agree to follow our Code of Conduct:

- [x] I follow Contributing Guidelines of this project.
- [x] I have checked the current issues for duplicate problems.
- [x] I have read the readme.

**Comment by bhartik021** [comment]
@AbhayaShankar assigned

**Comment by AbhayaShankar** [comment]
Please assign this, I think it's not assigned.

**Comment by AbhayaShankar** [comment]
Created a PR for the same, please review it and see if its good to merge @bhartik021
