### ISSUE TITLE
💡 [REQUEST] - Add an Open Source Resource

### ISSUE THREAD

**Issue by Sriparno08** [ZeroOctave/resource-gallery#110]
- [x] I am from GSSoC23.
- [x] I would like to be assigned this task.
* fill [x] to check the boxes.
---

| Section                    | Description |
|----------------------------|-------------|
| **Concise Description**    |I want to add a new Open Source resource|

### Code of Conduct

By submitting this issue, you agree to follow our Code of Conduct.

- [x] I follow the Contributing Guidelines of this project.
- [x] I have checked the current issues for duplicate problems.
- [x] I have read the readme of this repository.

**Comment by bhartik021** [comment]
@Sriparno08 assigned
