### ISSUE TITLE
Wanted to add my blog post related to DOM manipulation in JavaScript Resource Gallery

### ISSUE THREAD

**Issue by Prajwal0225** [ZeroOctave/resource-gallery#128]
### I wanted to add my blog post related to DOM manipulation in JavaScript Resource Gallery

![javascript resources](https://github.com/ZeroOctave/resource-gallery/assets/103810119/acd2656d-bb9b-4cc4-a5de-bfbb2983379a)

### blog post link: https://medium.com/@Prajwal25/what-is-dom-manipulation-33e5718cdcfa

I believe that this blog post would be a valuable addition to the Resource Gallery, providing helpful insights to fellow developers who are interested in learning about DOM manipulation in JavaScript.

### Published Link

blog post link: https://medium.com/@Prajwal25/what-is-dom-manipulation-33e5718cdcfa

### 🔄️ Websites

Medium

### Checklist ✅

- [X] I checked and didn't find similar issue
- [X] I am from GSSoC23
- [X] I have read the [Contributing Guidelines](https://github.com/ZeroOctave/resource-gallery/blob/main/CONTRIBUTION.md)
- [X] I am willing to work on this issue (blank for no)

**Comment by bhartik021** [comment]
@Prajwal0225 assigned
