### ISSUE TITLE
💡 [REQUEST] - Need for back to top button which matches the UI

### ISSUE THREAD

**Issue by saikiranreddy201** [ZeroOctave/resource-gallery#132]
- [x] I am from GSSoC23.
- [x] I would like to be assigned this task.
* fill [x] to check the boxes.
---

| Section                    | Description |
|----------------------------|-------------|
| **Concise Description**    |I believe that this website requires a back-to-top button that matches the UI of the webpage so that when the user is somewhere around the bottom of the page he can smoothly scroll back to the top of the page. |
| **Solution Proposed**      |Adding some logic and styling should work|
| **Screenshots**            |<img width="388" alt="Screenshot 2023-06-20 010821" src="https://github.com/ZeroOctave/resource-gallery/assets/98690105/4b4f7af3-a2bb-4557-ad71-42b5cfc76eb5">|

### Code of Conduct

By submitting this issue, you agree to follow our Code of Conduct.

- [x] I follow the Contributing Guidelines of this project.
- [x]I have checked the current issues for duplicate problems.
- [x]I  have read the readme of this repository.

**Comment by bhartik021** [comment]
@saikiranreddy201 assigned! make sure it should match with the UI
