### ISSUE TITLE
add readme badges

### ISSUE THREAD

**Issue by S-ishita** [ZeroOctave/resource-gallery#14]
I want to add readme badges.Please assign this issue to me under GSSOC.

**Comment by Astrodevil** [comment]
What type badges?

**Comment by S-ishita** [comment]
similar to this

![badges](https://github.com/ZeroOctave/resource-gallery/assets/104543751/d4475ad7-f100-4bd3-9d4a-f88b8891a556)

**Comment by Astrodevil** [comment]
Go ahead, but don't add too much badges. Only required ones
