### ISSUE TITLE
🐛 [BUG] - unclickable icons

### ISSUE THREAD

**Issue by k-deepak04** [ZeroOctave/resource-gallery#155]
## 🐛 Bug Report Form

the icons on the home page are not clickable 

![image](https://github.com/ZeroOctave/resource-gallery/assets/96341431/3a36c2b5-eeb1-4f05-ad73-b87bc5e161f4)

these icons only have a hover effect and are not clickable 
i want to add onclick event on them so they can work as a shortcut to go the resources quickly

🌐 **Browsers**
Which browsers are you experiencing the problem on? (Select all that apply)

- [x] Chrome
- [x] Firefox
- [x] Safari
- [x] Microsoft Edge
- [x] Opera
- [x] Brave

💻 **OS**
What is the impacted environment (operating system)? (Select all that apply)

- [x] Windows
- [ ] Linux
- [ ] Mac
- [ ] iOS
- [ ] Android

📝 **Sections Completed**
Check the box of the sections you have completed:

- [ ] Description
- [ ] Reproduction URL
- [ ] Reproduction Steps
- [ ] Screenshots
- [ ] Logs
- [ ] Browsers
- [ ] OS
- [ ] Additional Context

🔍 **Priority**
Please select the priority of the bug:
- [ ] High
- [x] Medium
- [ ] Low

📜 **Code of Conduct**
By submitting this issue, you agree to follow our Code of Conduct:

- [x] I follow Contributing Guidelines of this project.
- [x] I have checked the current issues for duplicate problems.
- [x] I have read the readme.

**Comment by subhamkumarr** [comment]
I would like to work on this, Please assign it to me
