### ISSUE TITLE
[Blog] Add New Blog on Open Source

### ISSUE THREAD

**Issue by Sriparno08** [ZeroOctave/resource-gallery#163]
### Description

I want to add a new open source blog to the website.

This blog lists the top 5 beginner-friendly GitHub repositories to contribute to.

### Published Link

https://sriparno.hashnode.dev/5-awesome-github-repositories-to-contribute-to

### 🔄️ Websites

Hashnode

### Checklist ✅

- [X] I checked and didn't find similar issue
- [X] I am from GSSoC23
- [X] I have read the [Contributing Guidelines](https://github.com/ZeroOctave/resource-gallery/blob/main/CONTRIBUTION.md)
- [X] I am willing to work on this issue (blank for no)

**Comment by subhamkumarr** [comment]
I would like to work on this, Please assign it to me
