### ISSUE TITLE
💡 [REQUEST] - <Adding Nextjs Blogs/Docs in resource Gallery..>

### ISSUE THREAD

**Issue by Shreya111111** [ZeroOctave/resource-gallery#168]
- [x] I am from GSSoC23.
- [x] I would like to be assigned this task.
* fill [x] to check the boxes.
---

| Section                    | Description |
|----------------------------|-------------|
| **Concise Description**    |Adding Nextjs Blogs/Docs in resource Gallery.. |
| **Solution Proposed**      |It will be adding in web development Section n contains the blogs/docs|

### Code of Conduct

By submitting this issue, you agree to follow our Code of Conduct.

- [x] I follow the Contributing Guidelines of this project.
- [x] I have checked the current issues for duplicate problems.
- [x] I have read the readme of this repository.

**Comment by Shreya111111** [comment]
@Astrodevil and @bhartik021 added three resources in web development shown in the screenshot above under issue https://github.com/ZeroOctave/resource-gallery/issues/168 and PR https://github.com/ZeroOctave/resource-gallery/pull/170 under gssoc'23. plz revieww it.

**Comment by Shreya111111** [comment]
@Astrodevil added three resources in web development shown in the screenshot above under issue https://github.com/ZeroOctave/resource-gallery/issues/168 and PR https://github.com/ZeroOctave/resource-gallery/pull/170 under gssoc'23. plz revieww it.

**Comment by Shreya111111** [comment]
@Alkaison plz review the issue https://github.com/ZeroOctave/resource-gallery/issues/168 and PR https://github.com/ZeroOctave/resource-gallery/pull/170 under gssoc'23.

**Comment by Alkaison** [comment]
Hi @Shreya111111, I have approved the changes soon @Astrodevil will merged it.
