### ISSUE TITLE
💡 [REQUEST] - <Creating the separate resources for cloud >

### ISSUE THREAD

**Issue by Shreya111111** [ZeroOctave/resource-gallery#169]
- [x] I am from GSSoC23.
- [x] I would like to be assigned this task.
* fill [x] to check the boxes.
---

| Section                    | Description |
|----------------------------|-------------|
| **Concise Description**    |Adding a new section of cloud in resource gallery.|
| **Solution Proposed**      |It will contain the  blogs/docs/other resources related to google/aws|

### Code of Conduct

By submitting this issue, you agree to follow our Code of Conduct.

- [x] I follow the Contributing Guidelines of this project.
- [x] I have checked the current issues for duplicate problems.
- [x] I have read the readme of this repository.

**Comment by Shreya111111** [comment]
@bhartik021 @Astrodevil @kartikkc plz review the issue https://github.com/ZeroOctave/resource-gallery/issues/169 and PR https://github.com/ZeroOctave/resource-gallery/pull/172 under gssoc'23

**Comment by Shreya111111** [comment]
@Astrodevil plz review the issue https://github.com/ZeroOctave/resource-gallery/issues/169 and PR https://github.com/ZeroOctave/resource-gallery/pull/172 under gssoc'23

**Comment by Alkaison** [comment]
Next time make sure you are more descriptive while providing the PR, Thanks @Shreya111111 Great work!
