### ISSUE TITLE
non scrolling navbar

### ISSUE THREAD

**Issue by anuza08** [ZeroOctave/resource-gallery#17]
Describe the bug
On every page of the website, the navbar is not scrolling down with the rest of the content. This can make it difficult for users to navigate the page, especially on smaller screens..

Expected behavior
The navbar should stay fixed at the top of the page so it remains visible at all times as the user scrolls down, allowing easy access to the website's navigation options.

***please allow me to solve this issue ***

**Comment by parasss19** [comment]
Hi @bhartik021 can you assign me this issue as i already implemented this in many other porjects

**Comment by bhartik021** [comment]
@parasss19 assigned
