### ISSUE TITLE
💡 [REQUEST] - adding search functionality in blogs section

### ISSUE THREAD

**Issue by Akanksha-202** [ZeroOctave/resource-gallery#184]
- [x] I am from GSSoC23.
- [x] I would like to be assigned this task.
* fill [x] to check the boxes.
---

| Section                    | Description |
|----------------------------|-------------|
| **Concise Description**    |There is no search bar for the user to search for a specific type of blog.|
| **Solution Proposed**      |I want to add a search bar to let users land to only those blogs in which they are interested.|
| **Alternative Solutions**  |Giving tags as filters for the user to display blogs over those topics only.|

### Code of Conduct

By submitting this issue, you agree to follow our Code of Conduct.

- [x] I follow the Contributing Guidelines of this project.
- [x] I have checked the current issues for duplicate problems.
- [x] I have read the readme of this repository.

**Comment by subhamkumarr** [comment]
I would like to work on this, Please assign it to me

**Comment by Akanksha-202** [comment]
Hey! @subhamkumarr! I've already mentioned while generating issue that i am willing to work over this if assigned:)

**Comment by bhartik021** [comment]
@Akanksha-202 assigned. Please make sure UI should matched
