### ISSUE TITLE
💡 [REQUEST] - Add NodeJS and MongoDB Resources 

### ISSUE THREAD

**Issue by siddarthdayala** [ZeroOctave/resource-gallery#190]
- [x] I am from GSSoC23.
- [x] I would like to be assigned this task.
* fill [x] to check the boxes.
---

| Section                    | Description |
|----------------------------|-------------|
| **Concise Description**    |Just wanted to add two websites regarding NodeJS and MongoDB in the Web Development Section |

### Code of Conduct

By submitting this issue, you agree to follow our Code of Conduct.

- [x] I follow the Contributing Guidelines of this project.
- [x] I have checked the current issues for duplicate problems.
- [x] I have read the readme of this repository.

**Comment by bhartik021** [comment]
@siddarthdayala assigned
