### ISSUE TITLE
💡 [REQUEST] - Resource page card design

### ISSUE THREAD

**Issue by BhartiNagpure** [ZeroOctave/resource-gallery#201]
- [x] I am from GSSoC23.
- [x] I would like to be assigned this task.
* fill [x] to check the boxes.
---

| Section                    | Description |
|----------------------------|-------------|
| **Concise Description**    |Card of resource page need to be change as its look dull.|
| **Solution Proposed**      |I would like to style card to give new look.
| **Alternative Solutions**  |Describe any alternative solutions you can think of|
| **Additional Context**     |Write any other contexts related to the feature request|
| **Screenshots**            |[Provide screenshots here]|

### Code of Conduct

By submitting this issue, you agree to follow our Code of Conduct.

- [x] I follow the Contributing Guidelines of this project.
- [] I have checked the current issues for duplicate problems.
- [x] I have read the readme of this repository.

**Comment by Alkaison** [comment]
Hi @BhartiNagpure, can you please provide a sample of the changes you want to purpose.

**Comment by BhartiNagpure** [comment]
![Screenshot 2023-07-10 221240](https://github.com/ZeroOctave/resource-gallery/assets/104631882/e02ae2b8-776a-4fe2-b21a-c08d3a58dc7b)

**Comment by subhamkumarr** [comment]
I would like to work on this, Please assign it to me

**Comment by Alkaison** [comment]
Hi @BhartiNagpure where do you want to purpose this changes? Like on which page can you provide URL because currently we don't have any cards matching the content you provided in image.

**Comment by BhartiNagpure** [comment]
On resources page I would to like change card style to make it attractive.  Above image are the sample .

**Comment by Alkaison** [comment]
- The current card design and hover effect is cool to be honest.

![image](https://github.com/ZeroOctave/resource-gallery/assets/98116504/8f29913d-3300-4553-8627-13c3f201d5fb)

**Comment by Astrodevil** [comment]
Yes, current card is perfect for current site design, proposed design looks outdated. please work on something new or try to add any important improvement @BhartiNagpure
