### ISSUE TITLE
💡 [REQUEST] - Adding a hover on social media icons

### ISSUE THREAD

**Issue by marshadkhn** [ZeroOctave/resource-gallery#207]
- [x] I am from GSSoC23.
- [x] I would like to be assigned this task.
---

| Section                    | Description |
|----------------------------|-------------|
| **Concise Description**    |Want to add a hover effect in the social media icons in footer|
| **Solution Proposed**      |The website is all good but there is something missing the footer section that is a hover effect on social links, not by size but a little change in the gradient so that user knows he/she is on that icon|
| **Screenshots**            |![image](https://github.com/ZeroOctave/resource-gallery/assets/80325579/d4e52f9b-91e4-42c0-b9a1-ae20017a7c90)|

### Code of Conduct

By submitting this issue, you agree to follow our Code of Conduct.

- [x] I follow the Contributing Guidelines of this project.
- [x] I have checked the current issues for duplicate problems.
- [x] I have read the readme of this repository.

**Comment by Alkaison** [comment]
Hi @marshadkhn, you can start working on this, we do expect something unique from you.

**Comment by marshadkhn** [comment]
Sure

**Comment by subhamkumarr** [comment]
I would like to work on this, Please assign it to me

**Comment by Alkaison** [comment]
Hi @subhamkumarr, this issue has already been assigned. Please look into other issues which aren't assigned to anyone yet.

**Comment by marshadkhn** [comment]
@subhamkumarr
I request you to add level in my issue as I am **GSSOC** contributor my rank will be counted as per score and score will increase wilL the level tag mention in issue

**Comment by Alkaison** [comment]
This issue has been completed by recent PR.
