### ISSUE TITLE
💡 [REQUEST] - Two same blog in the blog section of the website.

### ISSUE THREAD

**Issue by HimanshuNarware** [ZeroOctave/resource-gallery#209]
- [x] I am from GSSoC23.
- [x] I would like to be assigned this task.
* fill [x] to check the boxes.
---

| Section                    | Description |
|----------------------------|-------------|
| **Concise Description**    |Two same blogs in the blog section|
| **Solution Proposed**      |Want to remove one|
| **Screenshots**            |[ 
![51](https://github.com/ZeroOctave/resource-gallery/assets/83147410/7ccf6342-f01d-4e90-a365-4933f371f7a3)
  ]|

### Code of Conduct

By submitting this issue, you agree to follow our Code of Conduct.

- [x] I follow the Contributing Guidelines of this project.
- [x] I have checked the current issues for duplicate problems.
- [x] I have read the readme of this repository.

**Comment by Alkaison** [comment]
Hi @HimanshuNarware, thanks for reporting the issue and submitting the PR. soon it will be merged.
