### ISSUE TITLE
💡 [REQUEST] - Add Contributor page

### ISSUE THREAD

**Issue by SubhamB2003** [ZeroOctave/resource-gallery#211]
Hey, I want to add a contributor page to showcase all the contributors. If there is a need for that page then please assign this issue to me I want to work on it. I am a GSSOC'23 contributor.

**Comment by Alkaison** [comment]
Hi @SubhamB2003, it's a great idea to add a contributor's page on my website but we need confirmation from @Astrodevil for this. If he approves you will get assigned and you can work on it.

**Comment by SubhamB2003** [comment]
> Hi @SubhamB2003, it's a great idea to add a contributor's page on my website but we need confirmation from @Astrodevil for this. If he approves you will get assigned and you can work on it.

@Alkaison Yeah okay

**Comment by Astrodevil** [comment]
If about page is redesigned like, core team section looks bigger and below them contributors can add themselves.

Otherwise i don't want simple copy paste that readme code of contributors.

**Comment by SubhamB2003** [comment]
> 

Yeah I can add the contributors on the About page
