### ISSUE TITLE
💡 [REQUEST] - Fixing/Recreating/aligning About us cards 

### ISSUE THREAD

**Issue by ShreyaDhiman24** [ZeroOctave/resource-gallery#218]
- [x] I am from GSSoC23.
- [x] I would like to be assigned this task.
![Screenshot from 2023-07-13 18-20-29](https://github.com/ZeroOctave/resource-gallery/assets/98320971/17482d77-ae16-4b4a-9599-7f8f70717788)

| Section                    | Description |
|----------------------------|-------------|
| **Concise Description**    |Write a concise and appropriate description of the feature request |
| **Solution Proposed**      |Describe the solution you would want|
| **Alternative Solutions**  |Describe any alternative solutions you can think of|
| **Additional Context**     |Write any other contexts related to the feature request|
| **Screenshots**            |[Provide screenshots here]|

### Code of Conduct

By submitting this issue, you agree to follow our Code of Conduct.

- [x] I follow the Contributing Guidelines of this project.
- [x] I have checked the current issues for duplicate problems.
- [x] I have read the readme of this repository.

**Comment by Alkaison** [comment]
What changes you want to purpose?
Why this issue? Please describe it.
