### ISSUE TITLE
💡 [REQUEST] - <want to add favicon to this website >

### ISSUE THREAD

**Issue by g-rashmi** [ZeroOctave/resource-gallery#221]
-  I am from GSSoC23.
- [I would like to be assigned this task.

---

| Section                            | Description |

|   Concise Description    Add a favicon to the website for a visually appealing and recognizable icon in the browser tab. 
| Solution Proposed      Create or choose a suitable favicon image and add it to the website's  code. 

Code of Conduct

By submitting this issue, I agree to follow our Code of Conduct.

- I follow the Contributing Guidelines of this project.
-I have checked the current issues for duplicate problems.
- I have read the readme of this repository.

**Comment by Astrodevil** [comment]
its already there.
