### ISSUE TITLE
💡 Create a footer section 

### ISSUE THREAD

**Issue by akanksha984** [ZeroOctave/resource-gallery#225]
- [x ] I am from GSSoC23.
- [x ] I would like to be assigned this task.
* fill [x] to check the boxes.
---

I want to create a proper footer section for the page.
![image](https://github.com/ZeroOctave/resource-gallery/assets/97845909/c7eeb22d-f216-4e29-88a4-6a89998eab11)

### Code of Conduct

By submitting this issue, you agree to follow our Code of Conduct.

- [ x] I follow the Contributing Guidelines of this project.
- [ x] I have checked the current issues for duplicate problems.
- [ x] I have read the readme of this repository.

**Comment by Alkaison** [comment]
Someone is already working on this issue, so can't assign this to you. You can try contributing to a new feature.
