### ISSUE TITLE
💡 Cool Cards + section Improvement

### ISSUE THREAD

**Issue by akanksha984** [ZeroOctave/resource-gallery#226]
- [ x] I am from GSSoC23.
- [ x] I would like to be assigned this task.
* fill [x] to check the boxes.
---

I want to create cool cards so that the ui looks catchy and attractive.
I want to work on this issue, Please assign it to me under gssoc'23
![image](https://github.com/ZeroOctave/resource-gallery/assets/97845909/293a0dce-6d50-4570-8ae4-b344a8913964)
![image](https://github.com/ZeroOctave/resource-gallery/assets/97845909/dff3e10c-a137-409e-99d6-747a73b8ecf1)

### Code of Conduct

By submitting this issue, you agree to follow our Code of Conduct.

- [ x] I follow the Contributing Guidelines of this project.
- [ x] I have checked the current issues for duplicate problems.
- [ x] I have read the readme of this repository.

**Comment by Alkaison** [comment]
Hi @akanksha984, whatever you are trying to change it should match the website theme, can you please provide a sample example how your idea would look like?

**Comment by Alkaison** [comment]
Please provide the screenshots of your design idea by making changes locally and submit the screenshots here.

**Comment by akanksha984** [comment]
ya sure

**Comment by akanksha984** [comment]
![image](https://github.com/ZeroOctave/resource-gallery/assets/97845909/0a81fec9-873f-4ca6-acad-e0e449fe0761)
![image](https://github.com/ZeroOctave/resource-gallery/assets/97845909/1ba142e7-be11-4086-9681-d5e101aa20ea)

I want to add these hovers so that it looks stylish
@Alkaison

**Comment by Alkaison** [comment]
Hi @akanksha984, the images you provided are actually already under working face by another contributor. However, you can work on creating the UI design for the following image I have attached below. Let me know, if you agree with that. 🙂

![sample](https://user-images.githubusercontent.com/97845909/254555265-1ba142e7-be11-4086-9681-d5e101aa20ea.png)

**Comment by Alkaison** [comment]
Hi @akanksha984, the images you provided are actually already under working face by another contributor. However, you can work on creating the UI design for the following image I have attached below. Let me know, if you agree with that. 🙂

![sample](https://user-images.githubusercontent.com/97845909/254555265-1ba142e7-be11-4086-9681-d5e101aa20ea.png)

**Comment by Alkaison** [comment]
Hi @akanksha984, the images you provided are actually already under working face by another contributor. However, you can work on creating the UI design for the following image I have attached below. Let me know, if you agree with that. 🙂

![sample](https://user-images.githubusercontent.com/97845909/254555265-1ba142e7-be11-4086-9681-d5e101aa20ea.png)

**Comment by akanksha984** [comment]
ok sure, I have already improved it and other sections too. So should I create pr for this edit?

> Hi @akanksha984, the images you provided are actually already under working face by another contributor. However, you can work on creating the UI design for the following image I have attached below. Let me know, if you agree with that. 🙂
> 
> ![sample](https://user-images.githubusercontent.com/97845909/254555265-1ba142e7-be11-4086-9681-d5e101aa20ea.png)

**Comment by Alkaison** [comment]
Yes of course, also revert the changes for other edits.

**Comment by akanksha984** [comment]
https://github.com/ZeroOctave/resource-gallery/pull/236 Please check @Alkaison
