### ISSUE TITLE
💡 [REQUEST] - Add "The Odin Project"  in webdev.astro File in Pages Directory 

### ISSUE THREAD

**Issue by NarendraKoya999** [ZeroOctave/resource-gallery#239]
- [x] I am from GSSoC23.
- [x] I would like to be assigned this task.
* fill [x] to check the boxes.
---

| Section                    | Description |
|----------------------------|-------------|
| **Concise Description**    |Add "The Odin Project" in webdev.astro File in Pages Directory for Learning Web Development|
| **Solution Proposed**      |This Website is Truly Helpful for Who wants to Good Start in Web Development Career|
| **Alternative Solutions**  |Describe any alternative solutions you can think of|
| **Additional Context**     |This website is Most Underrated and Maintain Step By Step Course curriculum|
| **Screenshots**            |https://www.theodinproject.com/|

### Code of Conduct

By submitting this issue, you agree to follow our Code of Conduct.

- [x] I follow the Contributing Guidelines of this project.
- [x] I have checked the current issues for duplicate problems.
- [x] I have read the readme of this repository.

**Comment by Alkaison** [comment]
Hi @NarendraKoya999, you can contribute to the issue. Assigned ✅
