### ISSUE TITLE
💡 [REQUEST] - Add "Cisco Networking Academy" in javascript.astro File in Pages folder

### ISSUE THREAD

**Issue by NarendraKoya999** [ZeroOctave/resource-gallery#240]
- [x] I am from GSSoC23.
- [x] I would like to be assigned this task.
* fill [x] to check the boxes.
---

| Section                    | Description |
|----------------------------|-------------|
| **Concise Description**    |Add Cisco Networking Academy in javascript.astro File in Pages Folder |
| **Solution Proposed**      |This Course is very useful for Learning JavaScript Freshly . Specially, Benefits to Beginners|
| **Alternative Solutions**  |Describe any alternative solutions you can think of|
| **Additional Context**     |This Course is Free and value added to Personal portfolio for Everyone and Provide Certification|
| **Screenshots**            |https://www.netacad.com/|

### Code of Conduct

By submitting this issue, you agree to follow our Code of Conduct.

- [x] I follow the Contributing Guidelines of this project.
- [x] I have checked the current issues for duplicate problems.
- [x] I have read the readme of this repository.

**Comment by Alkaison** [comment]
Hi @NarendraKoya999, you can contribute to the issue. Assigned ✅
