### ISSUE TITLE
🐛 [BUG] - Suggest to add Modifications to avoid Minor Issues in frameworks.astro File in Pages Folder 

### ISSUE THREAD

**Issue by NarendraKoya999** [ZeroOctave/resource-gallery#241]
## GSSOC'23 Contributor
|                |                     |
|----------------|---------------------|
| **Description** | `In Frameworks Section, React and Vite added. Actually, these two are having different names not called Frameworks. But, you can put these two resources in Frameworks Section. I want to add /Libraries/Tools text along with Resource Gallery - Frameworks.....Text like sample one is- (Resource Gallery - Frameworks/Libraries/Tools) Like that`|

| **Reproduction URL** | https://resourcegallery.live/frameworks/|
| **Reproduction Steps** | 1. Go To https://resourcegallery.live/frameworks/<br>2. Observe `Frameworks` Section <br>3. Added `React.js and Vite Resources` in Frameworks Section<br>4. So, I suggest to change for Continuing of Frameworks Title to` add /Libraries/ Tools Text in Frameworks astro without Disturbing Our Content` to avoid Miss-Understanding for User Point of View|
| **Screenshots** | ![Screenshot 1]
![resourcegallery-2](https://github.com/ZeroOctave/resource-gallery/assets/84512164/5e690aec-c424-4b38-8664-8a79fe0d2034)
 |
| **Logs** | Relevant log output goes here |
| **Additional Context** | `For Clear Description of above Issue, React.js is a Library and Vite is a Build Tool. So, both these we are not called Frameworks. To avoid these conflicts. I suggest to add Some Modifications need for Title Bar in Frameworks Page` |

🌐 **Browsers**
Which browsers are you experiencing the problem on? (Select all that apply)

- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Opera
- [ ] Brave

💻 **OS**
What is the impacted environment (operating system)? (Select all that apply)

- [x] Windows
- [ ] Linux
- [ ] Mac
- [ ] iOS
- [ ] Android

📝 **Sections Completed**
Check the box of the sections you have completed:

- [x] Description
- [x] Reproduction URL
- [x] Reproduction Steps
- [x] Screenshots
- [ ] Logs
- [ ] Browsers
- [ ] OS
- [x] Additional Context

🔍 **Priority**
Please select the priority of the bug:
- [x] High
- [ ] Medium
- [ ] Low

📜 **Code of Conduct**
By submitting this issue, you agree to follow our Code of Conduct:

- [x] I follow Contributing Guidelines of this project.
- [x] I have checked the current issues for duplicate problems.
- [x] I have read the readme.

**Comment by Alkaison** [comment]
Hi @NarendraKoya999, Thanks for pointing the issue. 

Would you like to contribute and fix this issue? We can assign it to you or would give the chance to someone else.

**Comment by NarendraKoya999** [comment]
I want to work on this Issue @Alkaison
