### ISSUE TITLE
[Enhancement]: Improve "Margin-Top of Get Started Button" in cta.astro Section[Observe Screenshot]

### ISSUE THREAD

**Issue by NarendraKoya999** [ZeroOctave/resource-gallery#253]
### Issue Description:
- **Improve enhancement for `Get Started Button` in `cta.astro` File**
- **Because of, `Heading Text , Paragraph Text and Get Started Button` Closed together**

### Solution:
- **Add `Margin-Top of Heading , Paragraph Content below and Just above the Get Started Button`**

### Screenshots 
BEFORE CHANGES
![resourcegallery-3](https://github.com/ZeroOctave/resource-gallery/assets/84512164/13f2cb27-6234-408b-8772-8d188f7594ee)
AFTER CHANGES
![resourcegallery-4](https://github.com/ZeroOctave/resource-gallery/assets/84512164/3b4da591-eda2-4749-8156-0d1930a3f344)

**Comment by bhartik021** [comment]
@NarendraKoya999 assigned
