### ISSUE TITLE
  add "scroll to top" button on the home page.

### ISSUE THREAD

**Issue by Ujjwal-soni98** [ZeroOctave/resource-gallery#26]
Hola!! What's in my mind is that we can add "scroll to top" button on the home page for enhanced accessibility. 
I Want to add this functionality under GSSoC'23.
Kindly assign it to me :)

**Comment by vk20july** [comment]
@Astrodevil I want to work on this issue under gssoc'23

**Comment by Ujjwal-soni98** [comment]
hey @vk20july you can continue on this issue, i am unassigning this issue.

**Comment by vk20july** [comment]
> hey @vk20july you can continue on this issue, i am unassigning this issue.

@Astrodevil sir
