### ISSUE TITLE
💡 [REQUEST] - Add "DevDocs.io" Resource for Learning Variety of Technologies in Clean and Organized Manner

### ISSUE THREAD

**Issue by NarendraKoya999** [ZeroOctave/resource-gallery#260]
- [x] I am from GSSoC23.
- [x] I would like to be assigned this task.
* fill [x] to check the boxes.
---

| Section                    | Description |
|----------------------------|-------------|
| **Concise Description**    | Add "DevDocs.io" Resource for Learning Variety of Technologies in Clean and Organized Manner |
| **Solution Proposed**      |Describe the solution you would want|
| **Alternative Solutions**  |Describe any alternative solutions you can think of|
| **Additional Context**     |DevDocs.io combines multiple developer documentations in a clean and organized web UI with instant search, offline support, mobile version, dark theme, keyboard shortcuts, and more|
| **Screenshots**            |Please follow this Link for More Information :  https://devdocs.io/|

### Code of Conduct

By submitting this issue, you agree to follow our Code of Conduct.

- [x] I follow the Contributing Guidelines of this project.
- [x] I have checked the current issues for duplicate problems.
- [x] I have read the readme of this repository.

**Comment by Alkaison** [comment]
Try adding more than one resources. ✅

**Comment by NarendraKoya999** [comment]
> Try adding more than one resources. Assigned ✅

Ok Sure @Alkaison . I will try to make Multiple Similar Resources in One Issue
