### ISSUE TITLE
💡 [REQUEST] - Add new resources

### ISSUE THREAD

**Issue by k-deepak04** [ZeroOctave/resource-gallery#264]
- [x] I am from GSSoC23.
- [x] I would like to be assigned this task.
* fill [x] to check the boxes.
---

want to add resources for the frameworks
Add - 1) Angular
       -  2)Three-js
       - 3)Node-js

![image](https://github.com/ZeroOctave/resource-gallery/assets/96341431/e25155b3-49bc-4ae4-a248-f6b486c6967a)

as angular is much popular it must be present in the resources
and three js is the upcoming boom so we must include that too
### Code of Conduct

By submitting this issue, you agree to follow our Code of Conduct.

- [x] I follow the Contributing Guidelines of this project.
- [x] I have checked the current issues for duplicate problems.
- [x] I have read the readme of this repository.

**Comment by k-deepak04** [comment]
@bhartik021 please assign me with this i will qucikly do the needful and file the pr

**Comment by Alkaison** [comment]
@k-deepak04 go for it. 👍

**Comment by k-deepak04** [comment]
okay @Alkaison , please review and merge my previous pr, else i would need to create new branch
