### ISSUE TITLE
[Res]: Resources Gallery

### ISSUE THREAD

**Issue by Parul1606** [ZeroOctave/resource-gallery#282]
I would like to add New CSS Resource gallery. 
First of all add css section and then in it, other resources how to start with css, challenging websites for beginner to learn various topics of css, documentations, etc.

I will be adding websites: - 
https://www.w3.org/Style/CSS/learning
https://flexboxfroggy.com/
https://www.guess-css.app/
https://codepip.com/
and many more websites

I would like to work on this issue under gssoc

**Comment by Parul1606** [comment]
Please assign me. I would like to work on this issue @Alkaison

**Comment by Alkaison** [comment]
Hi @Parul1606, it's great you are adding multiple resources for CSS. Assigned ✅
