### ISSUE TITLE
Font Not Visible

### ISSUE THREAD

**Issue by kumarankit999** [ZeroOctave/resource-gallery#29]
As we can see below in this page ,We are not able to see the Name ,yt name, twitter name because it is also in black colour while in dark mode.
It should be in white color font.

![image](https://github.com/ZeroOctave/resource-gallery/assets/111564362/dfdc1035-0343-4f7b-8bf7-64374cfb9a63)

**Comment by bhartik021** [comment]
**fix:** Assigning issue #29 - Fix visibility issue of Name, YouTube name, and Twitter name in dark mode

**Comment by Astrodevil** [comment]
@kumarankit999 It's not on the resource gallery, This ss is of my personal site.
