### ISSUE TITLE
Add 'back-to-top' button in all pages

### ISSUE THREAD

**Issue by VSatwika** [ZeroOctave/resource-gallery#41]
- I would like to add a 'back-to-top' button in all the pages of the website to improve navigation and ease of use.
 
 - Could this issue be assigned to me under GSSoC'23?

**Comment by Ujjwal-soni98** [comment]
For adding "scroll to top button" on home page. 
I have been already assigned under #26 so it will be better if all the pages contain the same scroll to top. So it will better @bhartik021 if you close this issue.
