### ISSUE TITLE
Contributors Detail in /about page 

### ISSUE THREAD

**Issue by programerr01** [ZeroOctave/resource-gallery#57]
- [x] I am from GSSoC23.
- [x] I would like to be assigned this task.

I would like to add all the contributors details that are involved in this project

### Code of Conduct

By submitting this issue, you agree to follow our Code of Conduct.

- [x ] I follow the Contributing Guidelines of this project.
- [x] I have checked the current issues for duplicate problems.
- [x ] I have read the readme of this repository.

**Comment by mfatima05** [comment]
please assign this issue to me
