### ISSUE TITLE
💡 [ADD] - WEB-DEVELOPMENT RESOURCE

### ISSUE THREAD

**Issue by 0xabdulkhalid** [ZeroOctave/resource-gallery#64]
- [x] I am from GSSoC23.
- [x] I would like to be assigned this task.
---

| Section                    | Description |
|----------------------------|-------------|
| **Concise Description**    | React Documentation is lacking in Web-development resources  |
| **Solution Proposed**      | I'm gonna add best React Documentation out there to help beginners who starting to learn React |
| **Screenshot**| ![image](https://github.com/ZeroOctave/resource-gallery/assets/92252895/78dc00b5-4343-4ca2-95e9-4f6d5442107b) |

### Code of Conduct
- [x] I follow the Contributing Guidelines of this project.
- [x] I have checked the current issues for duplicate problems.
- [x] I have read the readme of this repository.

**Comment by 0xabdulkhalid** [comment]
@mfatima05, Already this issue has been in waiting stage.

Please create your own issue to contribute, commenting on other's issue is not appreciated.

**Comment by mfatima05** [comment]
> @mfatima05, Already this issue has been in waiting stage.
> 
> Please create your own issue to contribute, commenting on other's issue is not appreciated.

I read on internet that you have to solve the existing issue and as all issues get resolved then only you have to raise new issue

**Comment by Astrodevil** [comment]
> 

This is true if you have raised the issue before. Don't spam comments in every other issue.
