### ISSUE TITLE
Create PR Template

### ISSUE THREAD

**Issue by Astrodevil** [ZeroOctave/resource-gallery#66]
Create a good descriptive Pull Request template in .yml  so that new contributors can provide better information about their changes to the reviewer.

**Comment by ManasMadan** [comment]
Hi Please assign this issue to me under GSSoC 23

**Comment by ManasMadan** [comment]
Hi @Astrodevil, Please assign me this issue under GSSoC 23 and please brief me about what all you want in the template. I think PR Title, Description, Why this change, Screenshots, Types of Changes and some basic checklist to continue like have seen the code style, commented my code etc. would be fine

**Comment by Astrodevil** [comment]
Yes you are right! Try to put yml file as many contributors skips markdown information.

**Comment by ManasMadan** [comment]
@Astrodevil please review the PR #69. That PR closes this issue
