### ISSUE TITLE
[Blog]: ADD VUE.JS DOCUMENTATION RESOURCE FOR WEB-DEV

### ISSUE THREAD

**Issue by 0xabdulkhalid** [ZeroOctave/resource-gallery#71]
### Description

- This issue is about adding `Vue.js` framework's official documentation.
- It's one of the trending front end JavaScript framework for building user interfaces and single-page applications.

### Screenshot
![Vuejs](https://github.com/ZeroOctave/resource-gallery/assets/92252895/6db08cab-87bd-4fb9-9ce6-f1a019e8230d)

### Published Link

- Official Documentation of `Vue.js`: https://vuejs.org/

### 🔄️ Websites

Other

### Checklist ✅

- [X] I checked and didn't find similar issue
- [X] I am from GSSoC23
- [X] I have read the [Contributing Guidelines](https://github.com/ZeroOctave/resource-gallery/blob/main/CONTRIBUTION.md)
- [X] I am willing to work on this issue (blank for no)

**Comment by Astrodevil** [comment]
Add this in framework card and also move react docs from webdev to frameworks. Consider adding few more relevent resources.

**Comment by 0xabdulkhalid** [comment]
Yeah sure @Astrodevil, i will make the work done as per your request!
