### ISSUE TITLE
[Blog]: ADD NEW RESOURCES FOR FRAMEWORKS 💡

### ISSUE THREAD

**Issue by 0xabdulkhalid** [ZeroOctave/resource-gallery#75]
### Description

- This issue is about adding `Next.js` resource to the frameworks category

### Published Link

https://nextjs.org/

### 🔄️ Websites

Other

### Checklist ✅

- [X] I checked and didn't find similar issue
- [X] I am from GSSoC23
- [X] I have read the [Contributing Guidelines](https://github.com/ZeroOctave/resource-gallery/blob/main/CONTRIBUTION.md)
- [X] I am willing to work on this issue (blank for no)

**Comment by bhartik021** [comment]
@0xabdulkhalid assigned

**Comment by 0xabdulkhalid** [comment]
@bhartik021, you still not assigned me to this issue.

Please make sure to assign me, so that i can solve this issue.

**Comment by 0xabdulkhalid** [comment]
Hello @bhartik021, I have opened a PR for this issue.

Please make sure to check it out.
