### ISSUE TITLE
🐛 [BUG] -  add home in the navbar [GSSOC'23]

### ISSUE THREAD

**Issue by shivaniyuvrajyadav** [ZeroOctave/resource-gallery#77]
## 🐛 Bug Report Form

|                |                     |
|----------------|---------------------|
| **Description** | there is no option to redirect on home page |
| **Reproduction URL** | Please provide your GitHub URL to reproduce the issue |
https://github.com/shivaniyuvrajyadav
| **Screenshots** | ![Screenshot 1]
![image](https://github.com/ZeroOctave/resource-gallery/assets/112896644/47e1046d-0e23-43b4-b4b1-1d4e82cacb79)
 |

🌐 **Browsers**
Which browsers are you experiencing the problem on? (Select all that apply)

- [ ] Chrome
- [. ] Firefox
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Opera
- [ ] Brave

💻 **OS**
What is the impacted environment (operating system)? (Select all that apply)

- [. ] Windows
- [ ] Linux
- [ ] Mac
- [ ] iOS
- [ ] Android

📝 **Sections Completed**
Check the box of the sections you have completed:

- [. ] Description
- [. ] Reproduction URL
- [ ] Reproduction Steps
- [. ] Screenshots
- [ ] Logs
- [. ] Browsers
- [. ] OS
- [ ] Additional Context

🔍 **Priority**
Please select the priority of the bug:
- [. ] High
- [ ] Medium
- [ ] Low

📜 **Code of Conduct**
By submitting this issue, you agree to follow our Code of Conduct:

- [. ] I follow Contributing Guidelines of this project.
- [. ] I have checked the current issues for duplicate problems.
- [. ] I have read the readme.

**Comment by bhartik021** [comment]
@shivaniyuvrajyadav its is not required!
