### ISSUE TITLE
🐛 [BUG] - fixing header

### ISSUE THREAD

**Issue by OMKAR-KALEPU** [ZeroOctave/resource-gallery#80]
## 🐛 Bug Report Form

|                |                     |
|----------------|---------------------|
| **Description** | The header isn't full width which kind of looks ugly and also it is fixed but when scrolled the background is transparent so the other content kind of overlaps with header. |
| **Reproduction URL** | https://github.com/OMKAR-KALEPU |
| **Screenshots** | ![image](https://github.com/ZeroOctave/resource-gallery/assets/83866602/56ea2694-cea3-430c-8edb-0a8ea1d87f3d) |

🌐 **Browsers**
Which browsers are you experiencing the problem on? (Select all that apply)

- [x] Chrome
- [x] Firefox
- [x] Safari
- [x] Microsoft Edge
- [x] Opera
- [x] Brave

💻 **OS**
What is the impacted environment (operating system)? (Select all that apply)

- [x] Windows
- [ ] Linux
- [ ] Mac
- [ ] iOS
- [ ] Android

📝 **Sections Completed**
Check the box of the sections you have completed:

- [x] Description
- [x] Reproduction URL
- [ ] Reproduction Steps
- [x] Screenshots
- [ ] Logs
- [x] Browsers
- [x] OS
- [ ] Additional Context

🔍 **Priority**
Please select the priority of the bug:
- [ ] High
- [x] Medium
- [ ] Low

📜 **Code of Conduct**
By submitting this issue, you agree to follow our Code of Conduct:

- [x] I follow Contributing Guidelines of this project.
- [x] I have checked the current issues for duplicate problems.
- [x] I have read the readme.

Please assign this issue to me under GSOC23

**Comment by bhartik021** [comment]
@OMKAR-KALEPU assigned
