### ISSUE TITLE
Animation on Hero Section

### ISSUE THREAD

**Issue by parasss19** [ZeroOctave/resource-gallery#83]
- [ x ] am from GSSoC23.
- [ x ] I would like to be assigned this task.
* fill [x] to check the boxes.
---

| Section                    | Description |
|----------------------------|-------------|
| **Concise Description**    |Rignt the website hero section or I say landing page is so simple |
| **Solution Proposed**      |I think if we add some animation on hero section on loading the website it would be more attractive for users|
| **Alternative Solutions**  |I can add animation effects on hero section (both on text and image) As i already implemented animation in others projects also|
| **Additional Context**     |Write any other contexts related to the feature request|
| **Screenshots**            | |

### Code of Conduct

By submitting this issue, you agree to follow our Code of Conduct.

- [ x] I follow the Contributing Guidelines of this project.
- [x ] I have checked the current issues for duplicate problems.
- [x ] I have read the readme of this repository.

**Comment by bhartik021** [comment]
@parasss19 assigned
