### ISSUE TITLE
🐛 [BUG] - Z-Index Issue 

### ISSUE THREAD

**Issue by parthpathakpp1** [ZeroOctave/resource-gallery#92]
## 🐛 Bug Report Form

|                |                     |
|----------------|---------------------|
| **Description** | Z-index of navbar is low as compared to lot of things like images ,text , buttons in every page because of that everything is going on top of navbar while scrolling down .  |
| **Reproduction URL** | Please provide your GitHub URL to reproduce the issue |
| **Reproduction Steps** | 1. In every page scroll down you will see images , text , buttons going on top of the navbar . |
| **Screenshots** | 

https://github.com/ZeroOctave/resource-gallery/assets/85991449/7b89acf6-dbfd-47fc-b4c4-8f969a42156b

 |
🌐 **Browsers**
Which browsers are you experiencing the problem on? (Select all that apply)

- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Microsoft Edge
- [ ] Opera
- [ ] Brave

💻 **OS**
What is the impacted environment (operating system)? (Select all that apply)

- [x] Windows
- [ ] Linux
- [ ] Mac
- [ ] iOS
- [ ] Android

📝 **Sections Completed**
Check the box of the sections you have completed:

- [x] Description
- [ ] Reproduction URL
- [x] Reproduction Steps
- [x] Screenshots
- [ ] Logs
- [x] Browsers
- [x] OS
- [ ] Additional Context

🔍 **Priority**
Please select the priority of the bug:
- [x] High
- [ ] Medium
- [ ] Low

📜 **Code of Conduct**
By submitting this issue, you agree to follow our Code of Conduct:

- [x] I follow Contributing Guidelines of this project.
- [x] I have checked the current issues for duplicate problems.
- [x] I have read the readme.

**Comment by parthpathakpp1** [comment]
Can you assign this issue to me under GSSOC'23.

**Comment by bhartik021** [comment]
@parthpathakpp1 assigned

**Comment by parthpathakpp1** [comment]
I have raised a PR . Please Check.

**Comment by parthpathakpp1** [comment]
@Astrodevil I have raised a PR . Please Check https://github.com/ZeroOctave/resource-gallery/pull/97
