### ISSUE TITLE
💡 [Adding Resources] - <Adding Resources for learning Cybersecurity>

### ISSUE THREAD

**Issue by sangdeepganvir** [ZeroOctave/resource-gallery#98]
- [x ] I am from GSSoC23.
- [x ] I would like to be assigned this task.
* fill [x] to check the boxes.
---

| Section                    | Description |
|----------------------------|-------------|
| **Concise Description**    |I want to add a new section of Cybersecurity |
| **Solution Proposed**      |I want to add some resources to it also |
| **Additional Context**     |Resources include- Books, Videos|
### Code of Conduct

By submitting this issue, you agree to follow our Code of Conduct.

- [x ] I follow the Contributing Guidelines of this project.
- [ x] I have checked the current issues for duplicate problems.
- [ x] I have read the readme of this repository.

@kartikkc @Astrodevil @bhartik021 Please assign me this task under GSSOC'23 . Thank You

**Comment by bhartik021** [comment]
@sangdeepganvir assigned
